//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User_Data", Namespace="http://localhost:8080/Cont_End/")]
    public partial class User_Data : object
    {
        
        private string Tran_NameField;
        
        private string Work_GroupField;
        
        private string Tran_CodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Tran_Name
        {
            get
            {
                return this.Tran_NameField;
            }
            set
            {
                this.Tran_NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Work_Group
        {
            get
            {
                return this.Work_GroupField;
            }
            set
            {
                this.Work_GroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Tran_Code
        {
            get
            {
                return this.Tran_CodeField;
            }
            set
            {
                this.Tran_CodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://localhost:8080/Cont_End/")]
    public partial class Response : object
    {
        
        private string ZCIFRESULTField;
        
        private string ZERTNMSGField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ZCIFRESULT
        {
            get
            {
                return this.ZCIFRESULTField;
            }
            set
            {
                this.ZCIFRESULTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ZERTNMSG
        {
            get
            {
                return this.ZERTNMSGField;
            }
            set
            {
                this.ZERTNMSGField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="History", Namespace="http://localhost:8080/Cont_End/")]
    public partial class History : object
    {
        
        private string Container_NoField;
        
        private string Seal_NoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Container_No
        {
            get
            {
                return this.Container_NoField;
            }
            set
            {
                this.Container_NoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Seal_No
        {
            get
            {
                return this.Seal_NoField;
            }
            set
            {
                this.Seal_NoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8080/Cont_End/", ConfigurationName="ServiceReference1.Cont_Work_DSoap")]
    public interface Cont_Work_DSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Cont_End/Log_in", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.Log_inResponse> Log_inAsync(ServiceReference1.Log_inRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8080/Cont_End/Work_D_Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.Work_D_UpdateResponse> Work_D_UpdateAsync(ServiceReference1.Work_D_UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Log_inRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Log_in", Namespace="http://localhost:8080/Cont_End/", Order=0)]
        public ServiceReference1.Log_inRequestBody Body;
        
        public Log_inRequest()
        {
        }
        
        public Log_inRequest(ServiceReference1.Log_inRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:8080/Cont_End/")]
    public partial class Log_inRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string passWD;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ServiceReference1.User_Data[] tran_;
        
        public Log_inRequestBody()
        {
        }
        
        public Log_inRequestBody(string userID, string passWD, ServiceReference1.User_Data[] tran_)
        {
            this.userID = userID;
            this.passWD = passWD;
            this.tran_ = tran_;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Log_inResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Log_inResponse", Namespace="http://localhost:8080/Cont_End/", Order=0)]
        public ServiceReference1.Log_inResponseBody Body;
        
        public Log_inResponse()
        {
        }
        
        public Log_inResponse(ServiceReference1.Log_inResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:8080/Cont_End/")]
    public partial class Log_inResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Response Log_inResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ServiceReference1.User_Data[] tran_;
        
        public Log_inResponseBody()
        {
        }
        
        public Log_inResponseBody(ServiceReference1.Response Log_inResult, ServiceReference1.User_Data[] tran_)
        {
            this.Log_inResult = Log_inResult;
            this.tran_ = tran_;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Work_D_UpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Work_D_Update", Namespace="http://localhost:8080/Cont_End/", Order=0)]
        public ServiceReference1.Work_D_UpdateRequestBody Body;
        
        public Work_D_UpdateRequest()
        {
        }
        
        public Work_D_UpdateRequest(ServiceReference1.Work_D_UpdateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:8080/Cont_End/")]
    public partial class Work_D_UpdateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.History[] DATA;
        
        public Work_D_UpdateRequestBody()
        {
        }
        
        public Work_D_UpdateRequestBody(ServiceReference1.History[] DATA)
        {
            this.DATA = DATA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Work_D_UpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Work_D_UpdateResponse", Namespace="http://localhost:8080/Cont_End/", Order=0)]
        public ServiceReference1.Work_D_UpdateResponseBody Body;
        
        public Work_D_UpdateResponse()
        {
        }
        
        public Work_D_UpdateResponse(ServiceReference1.Work_D_UpdateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:8080/Cont_End/")]
    public partial class Work_D_UpdateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.Response Work_D_UpdateResult;
        
        public Work_D_UpdateResponseBody()
        {
        }
        
        public Work_D_UpdateResponseBody(ServiceReference1.Response Work_D_UpdateResult)
        {
            this.Work_D_UpdateResult = Work_D_UpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface Cont_Work_DSoapChannel : ServiceReference1.Cont_Work_DSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class Cont_Work_DSoapClient : System.ServiceModel.ClientBase<ServiceReference1.Cont_Work_DSoap>, ServiceReference1.Cont_Work_DSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Cont_Work_DSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Cont_Work_DSoapClient.GetBindingForEndpoint(endpointConfiguration), Cont_Work_DSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Cont_Work_DSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Cont_Work_DSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Cont_Work_DSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Cont_Work_DSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Cont_Work_DSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Log_inResponse> ServiceReference1.Cont_Work_DSoap.Log_inAsync(ServiceReference1.Log_inRequest request)
        {
            return base.Channel.Log_inAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Log_inResponse> Log_inAsync(string userID, string passWD, ServiceReference1.User_Data[] tran_)
        {
            ServiceReference1.Log_inRequest inValue = new ServiceReference1.Log_inRequest();
            inValue.Body = new ServiceReference1.Log_inRequestBody();
            inValue.Body.userID = userID;
            inValue.Body.passWD = passWD;
            inValue.Body.tran_ = tran_;
            return ((ServiceReference1.Cont_Work_DSoap)(this)).Log_inAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.Work_D_UpdateResponse> ServiceReference1.Cont_Work_DSoap.Work_D_UpdateAsync(ServiceReference1.Work_D_UpdateRequest request)
        {
            return base.Channel.Work_D_UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Work_D_UpdateResponse> Work_D_UpdateAsync(ServiceReference1.History[] DATA)
        {
            ServiceReference1.Work_D_UpdateRequest inValue = new ServiceReference1.Work_D_UpdateRequest();
            inValue.Body = new ServiceReference1.Work_D_UpdateRequestBody();
            inValue.Body.DATA = DATA;
            return ((ServiceReference1.Cont_Work_DSoap)(this)).Work_D_UpdateAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Cont_Work_DSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Cont_Work_DSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Cont_Work_DSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://14.63.160.64:8080/cont_end/cont_work_d.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Cont_Work_DSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://14.63.160.64:8080/cont_end/cont_work_d.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Cont_Work_DSoap,
            
            Cont_Work_DSoap12,
        }
    }
}
